# Generated by Django 2.1.3 on 2019-01-25 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('License_code', models.IntegerField(unique=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default=None, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('Temporary_Address', models.CharField(max_length=200)),
                ('Permanent_address', models.CharField(max_length=200)),
                ('Contact_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('Nationality', models.CharField(max_length=200)),
                ('Education_level', models.CharField(choices=[('SEE', 'see'), ('Bachelors', 'BACHELORS'), ('Master', 'MASTER')], default=None, max_length=200)),
                ('Citizenship', models.FileField(blank=True, default='No file uploaded', null=True, upload_to='uploads/')),
                ('Citizenship_number', models.IntegerField(unique=True)),
                ('Fathers_name', models.CharField(max_length=200)),
                ('Mothers_name', models.CharField(max_length=200)),
                ('Grandfathers_name', models.CharField(max_length=200)),
                ('Name_of_institution', models.CharField(blank=True, max_length=200)),
                ('Date_of_training', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('Bank_ac_no', models.IntegerField()),
                ('Bank_branch_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_number', models.IntegerField(unique=True)),
                ('Branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default=None, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('Temporary_Address', models.CharField(max_length=200)),
                ('Permanent_address', models.CharField(max_length=200)),
                ('Contact_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('Nationality', models.CharField(max_length=200)),
                ('Education_level', models.CharField(choices=[('see', 'SEE'), ('Bachelors', 'BACHELORS'), ('Master', 'MASTER')], default=None, max_length=200)),
                ('Citizenship', models.FileField(blank=True, default='No file uploaded', null=True, upload_to='uploads/')),
                ('Citizenship_number', models.IntegerField(unique=True)),
                ('Company_name', models.CharField(max_length=200)),
                ('Company_location', models.CharField(max_length=200)),
                ('Income_source', models.BigIntegerField()),
                ('Fathers_name', models.CharField(max_length=200)),
                ('Mothers_name', models.CharField(max_length=200)),
                ('Grandfathers_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('client_license_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='CMS.Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
